### ISSUE TITLE
Use a better typeface

### ISSUE THREAD

**Issue by alexgleason** [marykatefain/personalsite#12]
Selecting a better typeface will make a world of difference on this site. Maybe even two (one for headers, one for body).

**Comment by marykatefain** [comment]
Do you have a suggestion?

**Comment by alexgleason** [comment]
Browse fonts.google.com and set all type to say "Mary Kate Fain," find the one that works best then download it and embed it in the site

**Comment by marykatefain** [comment]
I know how to do that. I just didn't feel like doing it. Thanks for the help :P

**Comment by alexgleason** [comment]
It's your personal site. That's like telling you what clothes to wear.

**Comment by marykatefain** [comment]
I'm fine with the clothes I'm wearing. If you have an actual suggestion that's cool, but "I dont like your outfit" without any concrete suggestions is just being a bully.

**Comment by alexgleason** [comment]
The clothes you're wearing resemble a paper grocery bag.

>And fi­nally, font choice. The fastest, eas­i­est, and most vis­i­ble im­prove­ment you can make to your ty­pog­ra­phy is to ig­nore the fonts that came free with your com­puter (known as sys­tem fonts) and buy a pro­fes­sional font (like my fonts eq­uity and con­course, or oth­ers found in font rec­om­men­da­tions). A pro­fes­sional font gives you the ben­e­fit of a pro­fes­sional de­signer’s skills with­out hav­ing to hire one.
>
>If that’s im­pos­si­ble, you can still make good ty­pog­ra­phy with sys­tem fonts. But choose wisely. And never choose times new ro­man or Ar­ial, as those fonts are fa­vored only by the ap­a­thetic and sloppy. Not by ty­pog­ra­phers. Not by you.

—[Butterick's Practical Typography](http://practicaltypography.com/typography-in-ten-minutes.html)

**Comment by marykatefain** [comment]
At least I'm wearing pants right now.
