### ISSUE TITLE
Certificates lead to 404s

### ISSUE THREAD

**Issue by alexgleason** [marykatefain/personalsite#8]
http://marykatefain.surge.sh/assets/mary_kate_fain_HTML_cert.pdf
http://marykatefain.surge.sh/assets/mary_kate_fain_CSS.pdf
http://marykatefain.surge.sh/assets/mary_kate_fain_JS.pdf

**Comment by marykatefain** [comment]
https://github.com/sintaxi/surge/issues/257

Send in a request to be whitelisted.

**Comment by marykatefain** [comment]
Whitelisted
